routeEnhancers:
  RkwBasics:
    type: Extbase
    namespace: 'tx_coreextended_mediasources'
    routes:
      - routePath: '/coreextended/mediasources'
        _controller: 'MediaSources::list'
      - routePath: '/coreextended/mediasouces-page'
        _controller: 'MediaSources::listPage'
      - routePath: '/coreextended/sitemap'
        _controller: 'Google::sitemap'
    defaultController: 'MediaSources::list'
