services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Madj2k\CoreExtended\:
    resource: '../Classes/*'

  Madj2k\CoreExtended\Transfer\CsvImporter:
    public: true

  Madj2k\CoreExtended\Testing\FakeRequest:
    public: true
